[package]
name = "forge-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
forge-core.workspace = true
tokio.workspace = true
tracing.workspace = true
rand.workspace = true
regex-automata = "0.4"
serde_json.workspace = true
